<?php

namespace AppBundle\Repository;

/**
 * ContenuMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenuMailRepository extends \Doctrine\ORM\EntityRepository
{
}
