<?php

namespace AppBundle\Repository;

/**
 * ContenuMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenuMailRepository extends \Doctrine\ORM\EntityRepository
{
  public function findTexteWithStrong() {
    $qb = $this->createQueryBuilder('c');
    $qb->where(
                      $qb->expr()->like('c.contenuTxt', ':strong')
                  )
               ->setParameter('strong','%strong%');
    return $qb->getQuery()->getSingleResult();
   }
}
