<?php

namespace AppBundle\Repository;

/**
 * QuestionnaireQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionnaireQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
