<?php

namespace AppBundle\Repository;

/**
 * VoeuxProposeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoeuxProposeRepository extends \Doctrine\ORM\EntityRepository
{
}
