app_sendbestwishes:
    path:     /sendbestwishesbykoba
    defaults: { _controller: AppBundle:Admin:index }
    
app_frontpage:
    path:     /
    defaults: { _controller: AppBundle:Front:index }    
    
app_front_form:
    path:     /faites-vous-plaisir/{tokenmail}
    defaults: { _controller: AppBundle:Front:form }
    
app_front_merci:
    path:     /merci
    defaults: { _controller: AppBundle:Front:merci }
