app_frontpage:
    path:     /
    defaults: { _controller: AppBundle:Front:index }

#formulaire client
app_front_form:
    path:     /faites-vous-plaisir/{tokenmail}
    defaults: { _controller: AppBundle:Front:form }

#post soumission form
app_front_merci:
    path:     /merci
    defaults: { _controller: AppBundle:Front:merci }


#page d'administration
app_sendbestwishes:
    path:     /sendbestwishesbykoba
    defaults: { _controller: AppBundle:Admin:index }

#listing info csv
app_export_csv:
    path:     /exportcsv
    defaults: { _controller: AppBundle:Admin:exportcsv }

#listing info csv
app_import_csv_file_upload:
    path:     /import/upload
    defaults: { _controller: AppBundle:Import:upload }

#listing info csv
app_import_csv_check_validity:
    path:     /import/verification
    defaults: { _controller: AppBundle:Import:check_validity }

#mail online version
front_online_version:
    path:     /online/{type}/{hash}
    defaults: { _controller: AppBundle:Online:index }
